### PR TITLE
Clean update from Hungry Games Plus

### PR DESCRIPTION
**Pull request by Lymkwi**
### Reviewed :
- [x] Bucket (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/b7234d9242c1552247c2c7c1f97de494e5cc6eb7
- [x] Creative (validation 2/2) we don't merged it
- [x] Builtin_item (validation 2/2) No modifications needed
- [x] Default (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/74913caf67d850928fbc5d8aaf9fd4c818fea8ab https://github.com/LeMagnesium/hungry_games/commit/7e7ce5a2e04692aacd9dd1f0a0cf292937bc10f8 https://github.com/LeMagnesium/hungry_games/commit/e5c87fe7389bc4e77869edceee4622f1bdbb286b
- [x] Doors (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/a1975051b575c70d085254f24c303c397654b0af https://github.com/LeMagnesium/hungry_games/commit/d8a72ae248b5fda582079249fb2326ecd664956b
- [x] Fire (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/82d1967246aab34b9d8781ab45f1f46a60e434cb
- [x] Flowers (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/9d43640830d512b61271d6743685934d22524994 https://github.com/LeMagnesium/hungry_games/commit/fe004d13fbf421bf3203fc178123f7e7a5e1ea08
- [x] Hudbars (validation 2/2) No modifications needed
- [x] **Hungry Games** (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/07dbae147794adc993a0f8ebfe4d7455d12f047a https://github.com/LeMagnesium/hungry_games/commit/89f2f93b200010d0b406eaf033e660fb7c3f32ab https://github.com/LeMagnesium/hungry_games/commit/21c329878573646b5a21f75c15d2ff33a67b3ca3 https://github.com/LeMagnesium/hungry_games/commit/b3a5810f35fde27dffc021d328da80342cf50b9b
- [x] Inventory_Plus (validation 2/2) No modifications needed
- [x] Item_Drop (validation 2/2) No modifications needed
- [x] PlayerModel into Default (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/ee444905db5e8179b23359a605954b7f5273c470 https://github.com/LeMagnesium/hungry_games/commit/5e39ec13b66f55474460d714d2f158c7ecbf2be2 
- [x] Random Chests (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/d5630d0c3ad876d26dfe95faa4776fbb12806030
- [x] Stairs (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/5a3b48d3ebb474893093a586e8c6f43816530b4f https://github.com/LeMagnesium/hungry_games/commit/fc119a83b982e5cc33f7eae096c5f31f9a353659
- [x] Spawning (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/d5630d0c3ad876d26dfe95faa4776fbb12806030
- [x] Survival Modpack (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/30090ae32c7fdbe2d44f7abbccedf2abd82938b1
- [x] Vessels (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/225b3b340122b2eda3cbfedf5d01fbd259bb91a0
- [x] Wool (validation 2/2) https://github.com/LeMagnesium/hungry_games/commit/33a558f59e0a2c66b931f88d720c5766d248ffb9

(04/09/2015 à 10h27 par MFF : garde une trace écrite, même des mods pas à merger/supprimer suite à décision s'il te plaît :))

### CODE REVIEW

**Comment by ghost** [comment]
- Bucket  : **validated** for me
- Creative : **validated**  same as @Ombridride
- Builtin_item :**validated**
- Default: **validated**
- Doors: **validated**
- Fire: **validated** for me , no remove it, used by throwing mod, very useful to kill
- Flowers: **validated** for me, but "mushroom_spore" maybe useless?
- Hudbars: **validated**
- Hungry Games : **validated**
- Inventory_Plus: **validated**
- Item_Drop: **validated**
- PlayerModel :**validated** for me. "player:hud_set_hotbar "https://github.com/LeMagnesium/hungry_games/commit/ee444905db5e8179b23359a605954b7f5273c470#diff-ee5a751279baa5e37734fc0c1e75daf3R103  it's fixed this https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/8ee3e6398a8e26ccec83e8a41e574a64a1f769c3
- Random Chests: **validated**
- Stairs : **validated**, just missing textures or nodes removed of default? https://github.com/LeMagnesium/hungry_games/commit/5a3b48d3ebb474893093a586e8c6f43816530b4f#diff-d85e6749f6707aa8b7c089afb33ccdecR250 => https://github.com/LeMagnesium/hungry_games/commit/fc119a83b982e5cc33f7eae096c5f31f9a353659
- Spawning: **validated**
- Survival Modpack: **validated**
- Vessels: **validated**
- Wool: **validated**

**Comment by BetterToAutomateTheWorld** [comment]
- Bucket **validated** : ~~After discussion with @crabman77 and @gravgun, you can removed it, players doesn't need this mod and the admin can (with the creative inventory) takes sources when he wants. (the bucket for players add just a possibility to usebug), we need to removed useless mods like this one :)~~
- Creative **validated** : ~~Removed the diggable feature you add !!! It's NORMAL if we suppressed it ! (players doesn't need to dig ladders)~~
- Builtin_item **validated** : No modifications needed
- Default **validated**  : 
  - ~~Need to commented/removed pine_wood, pine_tree, acacia_wood, acacia_tree craft recipes.~~
  - ~~Commented/removed the furnace ABM.~~
  - ~~All tree trunks need to be indestructible.~~
  - ~~Cactus/papyrus/flowers/dry_shrub/junglegrass/grass_x/torch/ need to be unbreakable.~~
  - ~~Commented/removed bookshelf/vessels crafts. commented/removed all rails.~~
  - ~~default:meselamp needs to be unbreakable.~~
  - Validated because you fix all things i say earlier.
- Doors **validated** : ~~We need to removed every craft recipes~~ validated because now no more craft recipe
- Fire **validated** : ~~In my point of view, this mod is useless because not used, maybe removed it ?~~ Ok for the update, it's needed for the fire_arrow so we keep it ;)
- Flowers **validated** : ~~We need to comments(not removed) every ABM because maybe we will generate more than one arena area in the future, so we will maybe need to de-comment the ABM for map generation ;)~~ validated, because now the ABMs are commented. (You can removed the mushroom spore if you want)
- Hudbars **validated** : No modifications needed
- Hungry Games **validated** : 
  - ~~throwing:string and not farming:string https://github.com/MinetestForFun/server-minetestforfun-hungry_games/blob/813934641ae845d8b64f756693dd285f7809a938/mods/throwing/crafts.lua#L2 => https://github.com/LeMagnesium/hungry_games/commit/07dbae147794adc993a0f8ebfe4d7455d12f047a#diff-61e7d931e41c0109b3433cff3e8b2ebdL182~~
  - I hope your fix for vote/register commands works :)
- Inventory_Plus **validated** : No modifications needed
- Item_Drop **validated** : No modifications needed
- PlayerModel into Default **validated** : No modifications needed
- Random Chests **validated** : No modifications needed
- Stairs **validated** : ~~We need to removed every craft recipe~~ validated because now no more craft recipe
- Spawning **validated** : No modifications needed
- Survival Modpack **validated** : No modifications needed (the suit seems to be useless for us, but ok we keep it)
- Vessels **validated** : No modifications needed (some uply texture fore stee lvessels but we won't use it =))
- Wool **validated** : No modifications needed

**Comment by Lymkwi** [comment]
I will be clear and repeat what @crabman77 already warned us : 
**You cannot remove fire because it is used by fire arrows**, or maybe you want to remove it, and the fire arrows with it.

EDIT: Flowers reupdate with commented ABMs
EDIT2: Stairs has no craft recipes at the moment, just check the code, there's not any single one `minetest.register_craft` call...

**Comment by Lymkwi** [comment]
https://github.com/LeMagnesium/hungry_games/commit/d8a72ae248b5fda582079249fb2326ecd664956b
I commented doors' craft recipes.

**Comment by Lymkwi** [comment]
About your last check @Ombridride :
- I commented the pine/acacia nodes, but I didn't add their craft recipes
- I commented furnace active and furnace's ABM in the second commit
- Okay, they're unbreakable now
- Bookshelves don't have a craft recipe at the moment, and vessels is removed.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/04f6c2f253278e30627b28b3318be5d027ba42a7

**Pull request closed without merging**
